// Exercise
export const COLOR_SELECTED = 'COLOR_SELECTED';
export const TOOL_SELECTED = 'TOOL_SELECTED';
export const RESET_EXERCISE = 'RESET_EXERCISE';
export const LANDING_PALETTE_UPDATED = 'LANDING_PALETTE_UPDATED';
export const LANDING_CATEGORY_UPDATED = 'LANDING_CATEGORY_UPDATED';
export const LANDING_LIKE_BUTTON_CLICKED = 'LANDING_LIKE_BUTTON_CLICKED';
export const LANDING_UNDO_CLICKED = 'LANDING_UNDO_CLICKED';
export const LANDING_REDO_CLICKED = 'LANDING_REDO_CLICKED';
export const LANDING_DESIGN_LOADED = 'LANDING_DESIGN_LOADED';
export const LANDING_DESIGN_UNMOUNTED = 'LANDING_DESIGN_UNMOUNTED';
