// Exercise
export const COLOR_SELECTED = 'COLOR_SELECTED';
export const TOOL_SELECTED = 'TOOL_SELECTED';
export const RESET_EXERCISE = 'RESET_EXERCISE';
export const UPDATE_PALETTE = 'UPDATE_PALETTE';
