// Exercise
export const COLOR_SELECTED = 'COLOR_SELECTED';
export const TOOL_SELECTED = 'TOOL_SELECTED';
export const RESET_EXERCISE = 'RESET_EXERCISE';
export const LANDING_PALETTE_UPDATED = 'LANDING_PALETTE_UPDATED';
export const LANDING_CATEGORY_UPDATED = 'LANDING_CATEGORY_UPDATED';
export const LANDING_LIKE_BUTTON_CLICKED = 'LANDING_LIKE_BUTTON_CLICKED';
